# This is a basic workflow to help you get started with Actions

name: Main CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      # Test build
      - name: Compose Up
        run: docker-compose -f docker-compose.yml up -d
      
      - name: Check Running Containers
        run: docker ps -a
      
      - name: Check Logs
        run: docker-compose -f docker-compose.yml logs
      
      - name: Compose Down
        run: docker-compose -f docker-compose.yml down

      # Build both frontend and backend apps then push to ghcr
      - name: Build and Push Frontend
        id: build-push-frontend
        uses: docker/build-push-action@v2
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/front-end:latest
      
      - name: Build and Push Backend
        id: build-push-backend
        uses: docker/build-push-action@v2
        with:
          context: ./back-end
          file: ./back-end/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/back-end:latest
