name: Publish Releases to DockerHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/photo-repo-frontend:latest

      - name: Build and Push Backend
        uses: docker/build-push-action@v2
        with:
          context: ./back-end
          file: ./back-end/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/photo-repo-backend:latest
